### ISSUE TITLE
Error when running gulp on windows

### ISSUE THREAD

**Issue by Defoil** [stolksdorf/naturalcrit#91]
**Operating System**: Windows 10
**Issue Description**: 

When I run npm i the post install script `gulp prod` fails. When I run gulp prod manually I get the message that gulp-rename could not be found. I manually installed gulp-rename and then it said it could not find gulp-less. After that I could run gulp-prod without errors and after that I ran grunt fresh without problems. When I run gulp default I get an error.

```
[20:21:25] [nodemon] starting `node server.js`
C:\Users\Kevin\Desktop\naturalcrit\server\homebrew.api.js:73
                        invalidBrewQuery.remove().exec((err, objs){
                                                                 ^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Kevin\Desktop\naturalcrit\server.js:45:7)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by stolksdorf** [comment]
What version of node are you running?

**Comment by Defoil** [comment]
4.4.3

**Comment by stolksdorf** [comment]
Arrow functions should be supported in node +4.0

Line:73 has an arrow function in code, but it's missing from your stack trace. I can set the minimum required version of node in the `package.json`, if this is the issue.

**Comment by Defoil** [comment]
I fixed the problem by reinstalling node.

**Comment by stolksdorf** [comment]
Glad to hear! Thanks for taking the time to report this.
